// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ChaffModel.proto
#ifndef GRPC_ChaffModel_2eproto__INCLUDED
#define GRPC_ChaffModel_2eproto__INCLUDED

#include "ChaffModel.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class ChaffModel final {
 public:
  static constexpr char const* service_full_name() {
    return "ChaffModel";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status createChaff(::grpc::ClientContext* context, const ::ChaffCreateRequest& request, ::ResponseMessage* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ResponseMessage>> AsynccreateChaff(::grpc::ClientContext* context, const ::ChaffCreateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ResponseMessage>>(AsynccreateChaffRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ResponseMessage>> PrepareAsynccreateChaff(::grpc::ClientContext* context, const ::ChaffCreateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ResponseMessage>>(PrepareAsynccreateChaffRaw(context, request, cq));
    }
    virtual ::grpc::Status getChaffInfo(::grpc::ClientContext* context, const ::ChaffInfoRequest& request, ::ChaffInfo* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ChaffInfo>> AsyncgetChaffInfo(::grpc::ClientContext* context, const ::ChaffInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ChaffInfo>>(AsyncgetChaffInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ChaffInfo>> PrepareAsyncgetChaffInfo(::grpc::ClientContext* context, const ::ChaffInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ChaffInfo>>(PrepareAsyncgetChaffInfoRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void createChaff(::grpc::ClientContext* context, const ::ChaffCreateRequest* request, ::ResponseMessage* response, std::function<void(::grpc::Status)>) = 0;
      virtual void createChaff(::grpc::ClientContext* context, const ::ChaffCreateRequest* request, ::ResponseMessage* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void getChaffInfo(::grpc::ClientContext* context, const ::ChaffInfoRequest* request, ::ChaffInfo* response, std::function<void(::grpc::Status)>) = 0;
      virtual void getChaffInfo(::grpc::ClientContext* context, const ::ChaffInfoRequest* request, ::ChaffInfo* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ResponseMessage>* AsynccreateChaffRaw(::grpc::ClientContext* context, const ::ChaffCreateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ResponseMessage>* PrepareAsynccreateChaffRaw(::grpc::ClientContext* context, const ::ChaffCreateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ChaffInfo>* AsyncgetChaffInfoRaw(::grpc::ClientContext* context, const ::ChaffInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ChaffInfo>* PrepareAsyncgetChaffInfoRaw(::grpc::ClientContext* context, const ::ChaffInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status createChaff(::grpc::ClientContext* context, const ::ChaffCreateRequest& request, ::ResponseMessage* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ResponseMessage>> AsynccreateChaff(::grpc::ClientContext* context, const ::ChaffCreateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ResponseMessage>>(AsynccreateChaffRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ResponseMessage>> PrepareAsynccreateChaff(::grpc::ClientContext* context, const ::ChaffCreateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ResponseMessage>>(PrepareAsynccreateChaffRaw(context, request, cq));
    }
    ::grpc::Status getChaffInfo(::grpc::ClientContext* context, const ::ChaffInfoRequest& request, ::ChaffInfo* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ChaffInfo>> AsyncgetChaffInfo(::grpc::ClientContext* context, const ::ChaffInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ChaffInfo>>(AsyncgetChaffInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ChaffInfo>> PrepareAsyncgetChaffInfo(::grpc::ClientContext* context, const ::ChaffInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ChaffInfo>>(PrepareAsyncgetChaffInfoRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void createChaff(::grpc::ClientContext* context, const ::ChaffCreateRequest* request, ::ResponseMessage* response, std::function<void(::grpc::Status)>) override;
      void createChaff(::grpc::ClientContext* context, const ::ChaffCreateRequest* request, ::ResponseMessage* response, ::grpc::ClientUnaryReactor* reactor) override;
      void getChaffInfo(::grpc::ClientContext* context, const ::ChaffInfoRequest* request, ::ChaffInfo* response, std::function<void(::grpc::Status)>) override;
      void getChaffInfo(::grpc::ClientContext* context, const ::ChaffInfoRequest* request, ::ChaffInfo* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ResponseMessage>* AsynccreateChaffRaw(::grpc::ClientContext* context, const ::ChaffCreateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ResponseMessage>* PrepareAsynccreateChaffRaw(::grpc::ClientContext* context, const ::ChaffCreateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ChaffInfo>* AsyncgetChaffInfoRaw(::grpc::ClientContext* context, const ::ChaffInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ChaffInfo>* PrepareAsyncgetChaffInfoRaw(::grpc::ClientContext* context, const ::ChaffInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_createChaff_;
    const ::grpc::internal::RpcMethod rpcmethod_getChaffInfo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status createChaff(::grpc::ServerContext* context, const ::ChaffCreateRequest* request, ::ResponseMessage* response);
    virtual ::grpc::Status getChaffInfo(::grpc::ServerContext* context, const ::ChaffInfoRequest* request, ::ChaffInfo* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_createChaff : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_createChaff() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_createChaff() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status createChaff(::grpc::ServerContext* /*context*/, const ::ChaffCreateRequest* /*request*/, ::ResponseMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcreateChaff(::grpc::ServerContext* context, ::ChaffCreateRequest* request, ::grpc::ServerAsyncResponseWriter< ::ResponseMessage>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_getChaffInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_getChaffInfo() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_getChaffInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getChaffInfo(::grpc::ServerContext* /*context*/, const ::ChaffInfoRequest* /*request*/, ::ChaffInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetChaffInfo(::grpc::ServerContext* context, ::ChaffInfoRequest* request, ::grpc::ServerAsyncResponseWriter< ::ChaffInfo>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_createChaff<WithAsyncMethod_getChaffInfo<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_createChaff : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_createChaff() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ChaffCreateRequest, ::ResponseMessage>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ChaffCreateRequest* request, ::ResponseMessage* response) { return this->createChaff(context, request, response); }));}
    void SetMessageAllocatorFor_createChaff(
        ::grpc::MessageAllocator< ::ChaffCreateRequest, ::ResponseMessage>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ChaffCreateRequest, ::ResponseMessage>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_createChaff() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status createChaff(::grpc::ServerContext* /*context*/, const ::ChaffCreateRequest* /*request*/, ::ResponseMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* createChaff(
      ::grpc::CallbackServerContext* /*context*/, const ::ChaffCreateRequest* /*request*/, ::ResponseMessage* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_getChaffInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_getChaffInfo() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::ChaffInfoRequest, ::ChaffInfo>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ChaffInfoRequest* request, ::ChaffInfo* response) { return this->getChaffInfo(context, request, response); }));}
    void SetMessageAllocatorFor_getChaffInfo(
        ::grpc::MessageAllocator< ::ChaffInfoRequest, ::ChaffInfo>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ChaffInfoRequest, ::ChaffInfo>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_getChaffInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getChaffInfo(::grpc::ServerContext* /*context*/, const ::ChaffInfoRequest* /*request*/, ::ChaffInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* getChaffInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::ChaffInfoRequest* /*request*/, ::ChaffInfo* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_createChaff<WithCallbackMethod_getChaffInfo<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_createChaff : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_createChaff() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_createChaff() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status createChaff(::grpc::ServerContext* /*context*/, const ::ChaffCreateRequest* /*request*/, ::ResponseMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_getChaffInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_getChaffInfo() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_getChaffInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getChaffInfo(::grpc::ServerContext* /*context*/, const ::ChaffInfoRequest* /*request*/, ::ChaffInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_createChaff : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_createChaff() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_createChaff() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status createChaff(::grpc::ServerContext* /*context*/, const ::ChaffCreateRequest* /*request*/, ::ResponseMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcreateChaff(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_getChaffInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_getChaffInfo() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_getChaffInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getChaffInfo(::grpc::ServerContext* /*context*/, const ::ChaffInfoRequest* /*request*/, ::ChaffInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetChaffInfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_createChaff : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_createChaff() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->createChaff(context, request, response); }));
    }
    ~WithRawCallbackMethod_createChaff() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status createChaff(::grpc::ServerContext* /*context*/, const ::ChaffCreateRequest* /*request*/, ::ResponseMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* createChaff(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_getChaffInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_getChaffInfo() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->getChaffInfo(context, request, response); }));
    }
    ~WithRawCallbackMethod_getChaffInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getChaffInfo(::grpc::ServerContext* /*context*/, const ::ChaffInfoRequest* /*request*/, ::ChaffInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* getChaffInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_createChaff : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_createChaff() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ChaffCreateRequest, ::ResponseMessage>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ChaffCreateRequest, ::ResponseMessage>* streamer) {
                       return this->StreamedcreateChaff(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_createChaff() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status createChaff(::grpc::ServerContext* /*context*/, const ::ChaffCreateRequest* /*request*/, ::ResponseMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedcreateChaff(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ChaffCreateRequest,::ResponseMessage>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_getChaffInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_getChaffInfo() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ChaffInfoRequest, ::ChaffInfo>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ChaffInfoRequest, ::ChaffInfo>* streamer) {
                       return this->StreamedgetChaffInfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_getChaffInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status getChaffInfo(::grpc::ServerContext* /*context*/, const ::ChaffInfoRequest* /*request*/, ::ChaffInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedgetChaffInfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ChaffInfoRequest,::ChaffInfo>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_createChaff<WithStreamedUnaryMethod_getChaffInfo<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_createChaff<WithStreamedUnaryMethod_getChaffInfo<Service > > StreamedService;
};


#endif  // GRPC_ChaffModel_2eproto__INCLUDED
