// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChaffModel.proto

package org.example.grpc;

public final class ChaffModelOuterClass {
  private ChaffModelOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChaffCreateRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChaffCreateRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>double maxRCS = 2;</code>
     */
    double getMaxRCS();

    /**
     * <code>double T_c = 3;</code>
     */
    double getTC();

    /**
     * <code>double T_if = 4;</code>
     */
    double getTIf();

    /**
     * <code>double T_ef = 5;</code>
     */
    double getTEf();

    /**
     * <code>double T_trend = 6;</code>
     */
    double getTTrend();

    /**
     * <code>double CretionTime = 7;</code>
     */
    double getCretionTime();
  }
  /**
   * Protobuf type {@code ChaffCreateRequest}
   */
  public  static final class ChaffCreateRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChaffCreateRequest)
      ChaffCreateRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChaffCreateRequest.newBuilder() to construct.
    private ChaffCreateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChaffCreateRequest() {
      id_ = 0;
      maxRCS_ = 0D;
      tC_ = 0D;
      tIf_ = 0D;
      tEf_ = 0D;
      tTrend_ = 0D;
      cretionTime_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChaffCreateRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 17: {

              maxRCS_ = input.readDouble();
              break;
            }
            case 25: {

              tC_ = input.readDouble();
              break;
            }
            case 33: {

              tIf_ = input.readDouble();
              break;
            }
            case 41: {

              tEf_ = input.readDouble();
              break;
            }
            case 49: {

              tTrend_ = input.readDouble();
              break;
            }
            case 57: {

              cretionTime_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.grpc.ChaffModelOuterClass.internal_static_ChaffCreateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.grpc.ChaffModelOuterClass.internal_static_ChaffCreateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest.class, org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int MAXRCS_FIELD_NUMBER = 2;
    private double maxRCS_;
    /**
     * <code>double maxRCS = 2;</code>
     */
    public double getMaxRCS() {
      return maxRCS_;
    }

    public static final int T_C_FIELD_NUMBER = 3;
    private double tC_;
    /**
     * <code>double T_c = 3;</code>
     */
    public double getTC() {
      return tC_;
    }

    public static final int T_IF_FIELD_NUMBER = 4;
    private double tIf_;
    /**
     * <code>double T_if = 4;</code>
     */
    public double getTIf() {
      return tIf_;
    }

    public static final int T_EF_FIELD_NUMBER = 5;
    private double tEf_;
    /**
     * <code>double T_ef = 5;</code>
     */
    public double getTEf() {
      return tEf_;
    }

    public static final int T_TREND_FIELD_NUMBER = 6;
    private double tTrend_;
    /**
     * <code>double T_trend = 6;</code>
     */
    public double getTTrend() {
      return tTrend_;
    }

    public static final int CRETIONTIME_FIELD_NUMBER = 7;
    private double cretionTime_;
    /**
     * <code>double CretionTime = 7;</code>
     */
    public double getCretionTime() {
      return cretionTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (maxRCS_ != 0D) {
        output.writeDouble(2, maxRCS_);
      }
      if (tC_ != 0D) {
        output.writeDouble(3, tC_);
      }
      if (tIf_ != 0D) {
        output.writeDouble(4, tIf_);
      }
      if (tEf_ != 0D) {
        output.writeDouble(5, tEf_);
      }
      if (tTrend_ != 0D) {
        output.writeDouble(6, tTrend_);
      }
      if (cretionTime_ != 0D) {
        output.writeDouble(7, cretionTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (maxRCS_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, maxRCS_);
      }
      if (tC_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, tC_);
      }
      if (tIf_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, tIf_);
      }
      if (tEf_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, tEf_);
      }
      if (tTrend_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, tTrend_);
      }
      if (cretionTime_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, cretionTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest)) {
        return super.equals(obj);
      }
      org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest other = (org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (
          java.lang.Double.doubleToLongBits(getMaxRCS())
          == java.lang.Double.doubleToLongBits(
              other.getMaxRCS()));
      result = result && (
          java.lang.Double.doubleToLongBits(getTC())
          == java.lang.Double.doubleToLongBits(
              other.getTC()));
      result = result && (
          java.lang.Double.doubleToLongBits(getTIf())
          == java.lang.Double.doubleToLongBits(
              other.getTIf()));
      result = result && (
          java.lang.Double.doubleToLongBits(getTEf())
          == java.lang.Double.doubleToLongBits(
              other.getTEf()));
      result = result && (
          java.lang.Double.doubleToLongBits(getTTrend())
          == java.lang.Double.doubleToLongBits(
              other.getTTrend()));
      result = result && (
          java.lang.Double.doubleToLongBits(getCretionTime())
          == java.lang.Double.doubleToLongBits(
              other.getCretionTime()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + MAXRCS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMaxRCS()));
      hash = (37 * hash) + T_C_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTC()));
      hash = (37 * hash) + T_IF_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTIf()));
      hash = (37 * hash) + T_EF_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTEf()));
      hash = (37 * hash) + T_TREND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTTrend()));
      hash = (37 * hash) + CRETIONTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getCretionTime()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChaffCreateRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChaffCreateRequest)
        org.example.grpc.ChaffModelOuterClass.ChaffCreateRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.grpc.ChaffModelOuterClass.internal_static_ChaffCreateRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.grpc.ChaffModelOuterClass.internal_static_ChaffCreateRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest.class, org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest.Builder.class);
      }

      // Construct using org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        maxRCS_ = 0D;

        tC_ = 0D;

        tIf_ = 0D;

        tEf_ = 0D;

        tTrend_ = 0D;

        cretionTime_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.grpc.ChaffModelOuterClass.internal_static_ChaffCreateRequest_descriptor;
      }

      @java.lang.Override
      public org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest getDefaultInstanceForType() {
        return org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest build() {
        org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest buildPartial() {
        org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest result = new org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest(this);
        result.id_ = id_;
        result.maxRCS_ = maxRCS_;
        result.tC_ = tC_;
        result.tIf_ = tIf_;
        result.tEf_ = tEf_;
        result.tTrend_ = tTrend_;
        result.cretionTime_ = cretionTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest) {
          return mergeFrom((org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest other) {
        if (other == org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getMaxRCS() != 0D) {
          setMaxRCS(other.getMaxRCS());
        }
        if (other.getTC() != 0D) {
          setTC(other.getTC());
        }
        if (other.getTIf() != 0D) {
          setTIf(other.getTIf());
        }
        if (other.getTEf() != 0D) {
          setTEf(other.getTEf());
        }
        if (other.getTTrend() != 0D) {
          setTTrend(other.getTTrend());
        }
        if (other.getCretionTime() != 0D) {
          setCretionTime(other.getCretionTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private double maxRCS_ ;
      /**
       * <code>double maxRCS = 2;</code>
       */
      public double getMaxRCS() {
        return maxRCS_;
      }
      /**
       * <code>double maxRCS = 2;</code>
       */
      public Builder setMaxRCS(double value) {
        
        maxRCS_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double maxRCS = 2;</code>
       */
      public Builder clearMaxRCS() {
        
        maxRCS_ = 0D;
        onChanged();
        return this;
      }

      private double tC_ ;
      /**
       * <code>double T_c = 3;</code>
       */
      public double getTC() {
        return tC_;
      }
      /**
       * <code>double T_c = 3;</code>
       */
      public Builder setTC(double value) {
        
        tC_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double T_c = 3;</code>
       */
      public Builder clearTC() {
        
        tC_ = 0D;
        onChanged();
        return this;
      }

      private double tIf_ ;
      /**
       * <code>double T_if = 4;</code>
       */
      public double getTIf() {
        return tIf_;
      }
      /**
       * <code>double T_if = 4;</code>
       */
      public Builder setTIf(double value) {
        
        tIf_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double T_if = 4;</code>
       */
      public Builder clearTIf() {
        
        tIf_ = 0D;
        onChanged();
        return this;
      }

      private double tEf_ ;
      /**
       * <code>double T_ef = 5;</code>
       */
      public double getTEf() {
        return tEf_;
      }
      /**
       * <code>double T_ef = 5;</code>
       */
      public Builder setTEf(double value) {
        
        tEf_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double T_ef = 5;</code>
       */
      public Builder clearTEf() {
        
        tEf_ = 0D;
        onChanged();
        return this;
      }

      private double tTrend_ ;
      /**
       * <code>double T_trend = 6;</code>
       */
      public double getTTrend() {
        return tTrend_;
      }
      /**
       * <code>double T_trend = 6;</code>
       */
      public Builder setTTrend(double value) {
        
        tTrend_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double T_trend = 6;</code>
       */
      public Builder clearTTrend() {
        
        tTrend_ = 0D;
        onChanged();
        return this;
      }

      private double cretionTime_ ;
      /**
       * <code>double CretionTime = 7;</code>
       */
      public double getCretionTime() {
        return cretionTime_;
      }
      /**
       * <code>double CretionTime = 7;</code>
       */
      public Builder setCretionTime(double value) {
        
        cretionTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double CretionTime = 7;</code>
       */
      public Builder clearCretionTime() {
        
        cretionTime_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChaffCreateRequest)
    }

    // @@protoc_insertion_point(class_scope:ChaffCreateRequest)
    private static final org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest();
    }

    public static org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChaffCreateRequest>
        PARSER = new com.google.protobuf.AbstractParser<ChaffCreateRequest>() {
      @java.lang.Override
      public ChaffCreateRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChaffCreateRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChaffCreateRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChaffCreateRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.grpc.ChaffModelOuterClass.ChaffCreateRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string responseMessage = 1;</code>
     */
    java.lang.String getResponseMessage();
    /**
     * <code>string responseMessage = 1;</code>
     */
    com.google.protobuf.ByteString
        getResponseMessageBytes();
  }
  /**
   * Protobuf type {@code ResponseMessage}
   */
  public  static final class ResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResponseMessage)
      ResponseMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponseMessage.newBuilder() to construct.
    private ResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseMessage() {
      responseMessage_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              responseMessage_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.grpc.ChaffModelOuterClass.internal_static_ResponseMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.grpc.ChaffModelOuterClass.internal_static_ResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.grpc.ChaffModelOuterClass.ResponseMessage.class, org.example.grpc.ChaffModelOuterClass.ResponseMessage.Builder.class);
    }

    public static final int RESPONSEMESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object responseMessage_;
    /**
     * <code>string responseMessage = 1;</code>
     */
    public java.lang.String getResponseMessage() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string responseMessage = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResponseMessageBytes() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResponseMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, responseMessage_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResponseMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, responseMessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.grpc.ChaffModelOuterClass.ResponseMessage)) {
        return super.equals(obj);
      }
      org.example.grpc.ChaffModelOuterClass.ResponseMessage other = (org.example.grpc.ChaffModelOuterClass.ResponseMessage) obj;

      boolean result = true;
      result = result && getResponseMessage()
          .equals(other.getResponseMessage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSEMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.grpc.ChaffModelOuterClass.ResponseMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.grpc.ChaffModelOuterClass.ResponseMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.grpc.ChaffModelOuterClass.ResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.grpc.ChaffModelOuterClass.ResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.grpc.ChaffModelOuterClass.ResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.grpc.ChaffModelOuterClass.ResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.grpc.ChaffModelOuterClass.ResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.grpc.ChaffModelOuterClass.ResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.grpc.ChaffModelOuterClass.ResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.grpc.ChaffModelOuterClass.ResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.grpc.ChaffModelOuterClass.ResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.grpc.ChaffModelOuterClass.ResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.grpc.ChaffModelOuterClass.ResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResponseMessage)
        org.example.grpc.ChaffModelOuterClass.ResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.grpc.ChaffModelOuterClass.internal_static_ResponseMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.grpc.ChaffModelOuterClass.internal_static_ResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.grpc.ChaffModelOuterClass.ResponseMessage.class, org.example.grpc.ChaffModelOuterClass.ResponseMessage.Builder.class);
      }

      // Construct using org.example.grpc.ChaffModelOuterClass.ResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responseMessage_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.grpc.ChaffModelOuterClass.internal_static_ResponseMessage_descriptor;
      }

      @java.lang.Override
      public org.example.grpc.ChaffModelOuterClass.ResponseMessage getDefaultInstanceForType() {
        return org.example.grpc.ChaffModelOuterClass.ResponseMessage.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.grpc.ChaffModelOuterClass.ResponseMessage build() {
        org.example.grpc.ChaffModelOuterClass.ResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.grpc.ChaffModelOuterClass.ResponseMessage buildPartial() {
        org.example.grpc.ChaffModelOuterClass.ResponseMessage result = new org.example.grpc.ChaffModelOuterClass.ResponseMessage(this);
        result.responseMessage_ = responseMessage_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.grpc.ChaffModelOuterClass.ResponseMessage) {
          return mergeFrom((org.example.grpc.ChaffModelOuterClass.ResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.grpc.ChaffModelOuterClass.ResponseMessage other) {
        if (other == org.example.grpc.ChaffModelOuterClass.ResponseMessage.getDefaultInstance()) return this;
        if (!other.getResponseMessage().isEmpty()) {
          responseMessage_ = other.responseMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.grpc.ChaffModelOuterClass.ResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.grpc.ChaffModelOuterClass.ResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object responseMessage_ = "";
      /**
       * <code>string responseMessage = 1;</code>
       */
      public java.lang.String getResponseMessage() {
        java.lang.Object ref = responseMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string responseMessage = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResponseMessageBytes() {
        java.lang.Object ref = responseMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string responseMessage = 1;</code>
       */
      public Builder setResponseMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string responseMessage = 1;</code>
       */
      public Builder clearResponseMessage() {
        
        responseMessage_ = getDefaultInstance().getResponseMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string responseMessage = 1;</code>
       */
      public Builder setResponseMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responseMessage_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:ResponseMessage)
    private static final org.example.grpc.ChaffModelOuterClass.ResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.grpc.ChaffModelOuterClass.ResponseMessage();
    }

    public static org.example.grpc.ChaffModelOuterClass.ResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<ResponseMessage>() {
      @java.lang.Override
      public ResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.grpc.ChaffModelOuterClass.ResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChaffInfoRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChaffInfoRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>double SimulationTime = 2;</code>
     */
    double getSimulationTime();
  }
  /**
   * Protobuf type {@code ChaffInfoRequest}
   */
  public  static final class ChaffInfoRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChaffInfoRequest)
      ChaffInfoRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChaffInfoRequest.newBuilder() to construct.
    private ChaffInfoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChaffInfoRequest() {
      id_ = 0;
      simulationTime_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChaffInfoRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 17: {

              simulationTime_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.grpc.ChaffModelOuterClass.internal_static_ChaffInfoRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.grpc.ChaffModelOuterClass.internal_static_ChaffInfoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest.class, org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int SIMULATIONTIME_FIELD_NUMBER = 2;
    private double simulationTime_;
    /**
     * <code>double SimulationTime = 2;</code>
     */
    public double getSimulationTime() {
      return simulationTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (simulationTime_ != 0D) {
        output.writeDouble(2, simulationTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (simulationTime_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, simulationTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest)) {
        return super.equals(obj);
      }
      org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest other = (org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (
          java.lang.Double.doubleToLongBits(getSimulationTime())
          == java.lang.Double.doubleToLongBits(
              other.getSimulationTime()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + SIMULATIONTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSimulationTime()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChaffInfoRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChaffInfoRequest)
        org.example.grpc.ChaffModelOuterClass.ChaffInfoRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.grpc.ChaffModelOuterClass.internal_static_ChaffInfoRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.grpc.ChaffModelOuterClass.internal_static_ChaffInfoRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest.class, org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest.Builder.class);
      }

      // Construct using org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        simulationTime_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.grpc.ChaffModelOuterClass.internal_static_ChaffInfoRequest_descriptor;
      }

      @java.lang.Override
      public org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest getDefaultInstanceForType() {
        return org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest build() {
        org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest buildPartial() {
        org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest result = new org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest(this);
        result.id_ = id_;
        result.simulationTime_ = simulationTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest) {
          return mergeFrom((org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest other) {
        if (other == org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getSimulationTime() != 0D) {
          setSimulationTime(other.getSimulationTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private double simulationTime_ ;
      /**
       * <code>double SimulationTime = 2;</code>
       */
      public double getSimulationTime() {
        return simulationTime_;
      }
      /**
       * <code>double SimulationTime = 2;</code>
       */
      public Builder setSimulationTime(double value) {
        
        simulationTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double SimulationTime = 2;</code>
       */
      public Builder clearSimulationTime() {
        
        simulationTime_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChaffInfoRequest)
    }

    // @@protoc_insertion_point(class_scope:ChaffInfoRequest)
    private static final org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest();
    }

    public static org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChaffInfoRequest>
        PARSER = new com.google.protobuf.AbstractParser<ChaffInfoRequest>() {
      @java.lang.Override
      public ChaffInfoRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChaffInfoRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChaffInfoRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChaffInfoRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.grpc.ChaffModelOuterClass.ChaffInfoRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChaffInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChaffInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double RCS = 1;</code>
     */
    double getRCS();
  }
  /**
   * Protobuf type {@code ChaffInfo}
   */
  public  static final class ChaffInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChaffInfo)
      ChaffInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChaffInfo.newBuilder() to construct.
    private ChaffInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChaffInfo() {
      rCS_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChaffInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              rCS_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.grpc.ChaffModelOuterClass.internal_static_ChaffInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.grpc.ChaffModelOuterClass.internal_static_ChaffInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.grpc.ChaffModelOuterClass.ChaffInfo.class, org.example.grpc.ChaffModelOuterClass.ChaffInfo.Builder.class);
    }

    public static final int RCS_FIELD_NUMBER = 1;
    private double rCS_;
    /**
     * <code>double RCS = 1;</code>
     */
    public double getRCS() {
      return rCS_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rCS_ != 0D) {
        output.writeDouble(1, rCS_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rCS_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, rCS_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.grpc.ChaffModelOuterClass.ChaffInfo)) {
        return super.equals(obj);
      }
      org.example.grpc.ChaffModelOuterClass.ChaffInfo other = (org.example.grpc.ChaffModelOuterClass.ChaffInfo) obj;

      boolean result = true;
      result = result && (
          java.lang.Double.doubleToLongBits(getRCS())
          == java.lang.Double.doubleToLongBits(
              other.getRCS()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RCS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getRCS()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.grpc.ChaffModelOuterClass.ChaffInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.grpc.ChaffModelOuterClass.ChaffInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.grpc.ChaffModelOuterClass.ChaffInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChaffInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChaffInfo)
        org.example.grpc.ChaffModelOuterClass.ChaffInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.grpc.ChaffModelOuterClass.internal_static_ChaffInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.grpc.ChaffModelOuterClass.internal_static_ChaffInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.grpc.ChaffModelOuterClass.ChaffInfo.class, org.example.grpc.ChaffModelOuterClass.ChaffInfo.Builder.class);
      }

      // Construct using org.example.grpc.ChaffModelOuterClass.ChaffInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        rCS_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.grpc.ChaffModelOuterClass.internal_static_ChaffInfo_descriptor;
      }

      @java.lang.Override
      public org.example.grpc.ChaffModelOuterClass.ChaffInfo getDefaultInstanceForType() {
        return org.example.grpc.ChaffModelOuterClass.ChaffInfo.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.grpc.ChaffModelOuterClass.ChaffInfo build() {
        org.example.grpc.ChaffModelOuterClass.ChaffInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.grpc.ChaffModelOuterClass.ChaffInfo buildPartial() {
        org.example.grpc.ChaffModelOuterClass.ChaffInfo result = new org.example.grpc.ChaffModelOuterClass.ChaffInfo(this);
        result.rCS_ = rCS_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.grpc.ChaffModelOuterClass.ChaffInfo) {
          return mergeFrom((org.example.grpc.ChaffModelOuterClass.ChaffInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.grpc.ChaffModelOuterClass.ChaffInfo other) {
        if (other == org.example.grpc.ChaffModelOuterClass.ChaffInfo.getDefaultInstance()) return this;
        if (other.getRCS() != 0D) {
          setRCS(other.getRCS());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.grpc.ChaffModelOuterClass.ChaffInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.grpc.ChaffModelOuterClass.ChaffInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double rCS_ ;
      /**
       * <code>double RCS = 1;</code>
       */
      public double getRCS() {
        return rCS_;
      }
      /**
       * <code>double RCS = 1;</code>
       */
      public Builder setRCS(double value) {
        
        rCS_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double RCS = 1;</code>
       */
      public Builder clearRCS() {
        
        rCS_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChaffInfo)
    }

    // @@protoc_insertion_point(class_scope:ChaffInfo)
    private static final org.example.grpc.ChaffModelOuterClass.ChaffInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.grpc.ChaffModelOuterClass.ChaffInfo();
    }

    public static org.example.grpc.ChaffModelOuterClass.ChaffInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChaffInfo>
        PARSER = new com.google.protobuf.AbstractParser<ChaffInfo>() {
      @java.lang.Override
      public ChaffInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChaffInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChaffInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChaffInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.grpc.ChaffModelOuterClass.ChaffInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChaffCreateRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChaffCreateRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChaffInfoRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChaffInfoRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChaffInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChaffInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ChaffModel.proto\"\177\n\022ChaffCreateRequest" +
      "\022\n\n\002id\030\001 \001(\005\022\016\n\006maxRCS\030\002 \001(\001\022\013\n\003T_c\030\003 \001(" +
      "\001\022\014\n\004T_if\030\004 \001(\001\022\014\n\004T_ef\030\005 \001(\001\022\017\n\007T_trend" +
      "\030\006 \001(\001\022\023\n\013CretionTime\030\007 \001(\001\"*\n\017ResponseM" +
      "essage\022\027\n\017responseMessage\030\001 \001(\t\"6\n\020Chaff" +
      "InfoRequest\022\n\n\002id\030\001 \001(\005\022\026\n\016SimulationTim" +
      "e\030\002 \001(\001\"\030\n\tChaffInfo\022\013\n\003RCS\030\001 \001(\0012q\n\nCha" +
      "ffModel\0224\n\013createChaff\022\023.ChaffCreateRequ" +
      "est\032\020.ResponseMessage\022-\n\014getChaffInfo\022\021." +
      "ChaffInfoRequest\032\n.ChaffInfoB\022\n\020org.exam" +
      "ple.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ChaffCreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChaffCreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChaffCreateRequest_descriptor,
        new java.lang.String[] { "Id", "MaxRCS", "TC", "TIf", "TEf", "TTrend", "CretionTime", });
    internal_static_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseMessage_descriptor,
        new java.lang.String[] { "ResponseMessage", });
    internal_static_ChaffInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ChaffInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChaffInfoRequest_descriptor,
        new java.lang.String[] { "Id", "SimulationTime", });
    internal_static_ChaffInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ChaffInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChaffInfo_descriptor,
        new java.lang.String[] { "RCS", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
